sonar.projectKey=E-Shop-Symfony
sonar.projectName=E Shop Symfony

sonar.sources=src
sonar.tests=tests
sonar.exclusions=vendor/**,var/**,public/build/**

sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.php.tests.reportPath=coverage/junit.xml
