server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php index.html;
    client_max_body_size 32m;

    # Temp dirs accessibles par nginx non-root
    client_body_temp_path  /tmp/nginx/client_temp;
    proxy_temp_path        /tmp/nginx/proxy_temp;
    fastcgi_temp_path      /tmp/nginx/fastcgi_temp;
    uwsgi_temp_path        /tmp/nginx/uwsgi_temp;
    scgi_temp_path         /tmp/nginx/scgi_temp;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_read_timeout 60s;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}