apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-shop-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: e-shop-app
  template:
    metadata:
      labels:
        app: e-shop-app
    spec:

      serviceAccountName: {{ .Values.serviceAccount.name }}

      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}

      containers:
        - name: app
          image: "{{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}

          ports:
            - containerPort: 80

          resources:
            {{- toYaml .Values.resources.app | nindent 12 }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          env:
            - name: APP_ENV
              value: {{ .Values.env.appEnv | quote }}
            - name: APP_DEBUG
              value: {{ .Values.env.appDebug | quote }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: e-shop-migrations
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    spec:

      restartPolicy: Never

      serviceAccountName: {{ .Values.serviceAccount.name }}

      securityContext:
        {{- toYaml .Values.migrations.securityContext | nindent 8 }}

      containers:
        - name: migrations
          image: "{{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}"

          command: ["sh", "-c", "php artisan migrate"]

          securityContext:
            {{- toYaml .Values.migrations.securityContext | nindent 12 }}

          env:
            - name: APP_ENV
              value: {{ .Values.env.appEnv | quote }}