{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: e-shop-runtime
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: e-shop-runtime
    creationPolicy: Owner
  data:
    - secretKey: app_secret
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretName }}
        property: app_secret
    - secretKey: database_url
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretName }}
        property: database_url
{{- end }}
